vich_uploader:
    db_driver: orm

    mappings:
        content_game:
            uri_prefix: /games
            upload_destination: '%kernel.project_dir%/public/games'
            
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true